import "./globals.css";
import SparklesIcon from "@/components/SparklesIcon";
// import { Poppins } from "next/font/google";
import Link from "next/link";
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={inter.className + " bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen text-white"}
        className={" text-white bg-gradient-animation"}
      >
        <Navbar />
        <main className="p-4 mx-auto">
          {/* <header className="flex justify-between my-2 sm:my-8">
            <Link href="/" className="flex gap-1">
              <SparklesIcon />
              <span>AiSolutions</span>
            </Link>
            <nav className="flex items-center gap-2 sm:gap-6 text-white/80 text-sm sm:text-bas">
              <Link href="/">Home</Link>
              <Link href="/pricing">Pricing</Link>
              <a href="mailto:contact@epiccaptions.com">Contact</a>
            </nav>
          </header> */}
          {children}
        </main>
      </body>
    </html>
  );
}
